### ISSUE TITLE
Neighborhood Study Rezoning Commitments are not rolled up to the record-level

### ISSUE THREAD

**Issue by mshapiro1** [NYCPlanning/db-knownprojects#101]
Neighborhood Study Rezoning Commitments and their BBLs should be rolled up to the record-level, but they're currently not (see record_name: "EAST NEW YORK: Christopher-Glenmore"). I'm guessing this is because, since the last run, we've assigned new record IDs to this source, and these distinct record IDs have kept the records from aggregating as they should.

It would be helpful if this could be addressed before flowing through to the DOB cluster review.

**Comment by mgraber** [comment]
Change `geom_merge` as ST_Union on `GROUP BY neighborhood_study`.

**Comment by mgraber** [comment]
This is fixed in the database. To avoid redoing the cluster review process, merge corrected n_study_proj table with clusters_unresolved_2020 on `record_name`. Review rows will be retained, but the corrected `record_id`, `units_gross`, and `geom` will come from the corrected n_study_proj table.
