### ISSUE TITLE
null unit values from projects that have units in the raw data

### ISSUE THREAD

**Issue by mshapiro1** [NYCPlanning/db-knownprojects#102]
HPD RFP record_name: "NYCHA Holmes" has a null unit value in the cluster 1 review table, but the raw data shows a unit value for this record. It is possible this error is occurring for other records as well.

**Comment by mgraber** [comment]
Hi @mshapiro1, are you referring to record_id: ffee0270521a5dcfba96ab6cd042508c ?
In our input data table, this ID has `est_units` of '-', which we are interpreting as NULL.

Do you have a different example I can investigate?

**Comment by mshapiro1** [comment]
@mgraber  Apologies, this issue was a mistake! it can be closed 

I was looking at last year's source, where the above project had a unit count. in this year's data, its unit count is null
