### ISSUE TITLE
Updated unit counts from the corrections table may not be flowing through  

### ISSUE THREAD

**Issue by mshapiro1** [NYCPlanning/db-knownprojects#103]
Updated unit count for record ID P2005M0053, which was placed in the corrections table before the cluster 1 review table was created, did not flow through to the cluster 1 review table.

I don't know if this is an error, or part of the process. Flagging in case it's an error!

**Comment by mgraber** [comment]
As of now, we have 3 `units_gross` corrections that are all being applied. @mshapiro1 are there corrections to unit counts that you've created since 4/29/20?

**Comment by mshapiro1** [comment]
@mgraber Apologies, this issue was a mistake! it can be closed
