### ISSUE TITLE
Translate proportion phasing columns to count phasing columns

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#120]
Based on the [agreed-upon schema](https://github.com/NYCPlanning/db-knownprojects/wiki/KPDB-Schema), the final kpdb table should only have count columns for phasing, which are calculated by multiplying the proportion phasing columns by a unit count field.

**Input needed: Should the phasing counts be based on units_gross for each record or units_net?**

**Comment by mshapiro1** [comment]
@mgraber units_net, given that these are the units we're counted in a future pipeline. If we did units_gross, we'd be double counting.

@levysamu looking for your confirmation

**Comment by mgraber** [comment]
@mshapiro1, I'd like to point out that if we use units_net, the assumption is that we can't trust the original phasing data for any record that has units deduped by a higher priority record.

For example, a record with 200 units has phasing 0.25 (within 5), 0.25 (5 to 10), 0.5 (more than 10).
A higher-"certainty" record with 150 units has phasing 1 (within 5), 0 (5 to 10), 0 (more than 10).

The deduped records would look like this:
Low-"certainty": 50 units, 0.25, 0.25, 0.5
High-"certainty": 150 units, 1, 0, 0

In this case, we are saying that those 150 units that get deduped in the lower-certainty bin are phased incorrectly, simply because they are double-counted. They go from a phasing that is mostly long-term to a phasing that is not at all long-term. Is this reasonable?

**Comment by mshapiro1** [comment]
@mgraber that's the correct logic, yes. We're assuming that, once a unit appears in a higher certainty source, it's likely to materialize earlier (based on the best info we have).

cc @levysamu

**Comment by AmandaDoyle** [comment]
Confirmation that we'll just be multiplying units_net by the porportion
