### ISSUE TITLE
Update date value for Neighborhood Study Projected Development Sites

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#126]
The source data did not include the Effective Date for records.  Below is the effective date for each record.  The effective date is needed to compute the phasing.  My recommendation is to 1) update the source data so that it's captured somewhere, and then manually edit the values in the final / near final KPDB table

Neighborhood | Effective Date
-- | --
Bay Street Corridor | 7/1/2019
Downtown Far Rockaway | 9/7/2017
East Harlem | 11/30/2017
East New York | 4/20/2016
Inwood | 3/22/2018
Jerome | 1/16/2018

**Comment by mgraber** [comment]
@AmandaDoyle  Because this source doesn't get appended to kpdb until the very end, we can simply add these to the _proj table. No need for manual edits. These records are not in the workflow yet anyway.

**Comment by AmandaDoyle** [comment]
ah okay great.  Thanks

**Comment by mgraber** [comment]
Data is updated in build database. Getting confirmation on future date formats before adding to dcp_n_study_projected.sql
