### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#130]
Manual review:
- [x] How to fill in the manual corrections table
- the different corrections that can be made
- the fields that are dependent on each other
- [x] How to complete the Planner Added Projects table
- [x] How to deliver corrected geometries (shapefile with project ID column)

General:
- [ ] Technical documentation on how to build KPDB 
- [x] Procedural documentation on how to build KPDB (the manual research steps)

**Comment by mgraber** [comment]
- For manual corrections documentation, add dependencies to [existing wiki page](https://github.com/NYCPlanning/db-knownprojects/wiki/KPDB-Corrections-Process)
- Create wiki page for planner added projects
- Create wiki for geometry corrections, with links to geojson.io

@AmandaDoyle  Can you explain the difference between the technical and procedural documentation on how to build KPDB? Who is the intended audience for each?

**Comment by AmandaDoyle** [comment]
@mgraber Audience for technical documentation would be data engineering.  Audience for procedural documentation would be data engineering and product partner (CP and HED)

**Comment by SPTKL** [comment]
I kind of did a simple procedural page on the wiki 
https://github.com/NYCPlanning/db-knownprojects/wiki/Build-Process
of course, each step would need a lot of clarification

**Comment by AmandaDoyle** [comment]
@SPTKL okay great.
I'm writing the remaining pieces of the Manual review documentation and tieing them together

**Comment by mgraber** [comment]
Should the technical documentation (for Data Engineering) live in the main README rather than the Wiki?

**Comment by SPTKL** [comment]
let's put it in a `maintenance` folder under root?
or we can do both

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/db-knownprojects/wiki/Build-environment-tables
