### ISSUE TITLE
Should ."2020" be the table name in the build process?

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#131]
We won't want to update the queries each time we create a new version, so should the table just be kpdb_gross and not kpdb_gross."2020"?

**Comment by mgraber** [comment]
@AmandaDoyle  Perhaps this relates to #105? We already use versioning for the uploads and downloads with Carto.

**Comment by mgraber** [comment]
Suggestion:
- Keep all review tables on carto versioned
- Keep all review results versioned
- Keep cluster tables versioned
- Remove versioning from kpdb_gross

Versioning that happens in python, rather than sql, is easy to update.

**Comment by SPTKL** [comment]
e.g. https://github.com/NYCPlanning/db-pluto/blob/ac17a488c4ce7a150d8b83bba6a44b18484881d7/pluto_build/sql/create.sql#L89

we can just set the environmental variable somewhere with a `.env` file
e.g. `VERSION=2020`
execute using
```bash
psql $BUILD_ENGINE -v version=$VERSION -f sql/file.sql
```
to pass the variable into the .sql file
