### ISSUE TITLE
Assign cluster_id using SQL instead of python -> Cluster 1

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-knownprojects#141]
### current work flow: 
1. pull reviewed_clusters to db
2. dispatch cluster id and sub cluster id, units_net (in python)
3. then combine sources tables, and proceed to DOB match

### proposed work flow: 
1. pull reviewed_cluster to db
2. combine source tables, dispatch cluster id and sub cluster id, units_net (in sql)
3. proceed to DOB match

### Example:
Example logic on last year's table:
```sql
SELECT *,
         ST_ClusterDBSCAN(geom, 0, 1) OVER() AS _cluster_id
  FROM   kpdb_2020.combined
```
QA to show that the clusters are 1-1 matches
```sql
select cluster_id, count(*)
from (
SELECT
	cluster_id,
	_cluster_id
FROM   (
  SELECT *,
         ST_ClusterDBSCAN(geom, 0, 1) OVER() AS _cluster_id
  FROM   kpdb_2020.combined
  ) q
group by cluster_id, _cluster_id ) b
group by cluster_id
```
replacing `03.1_clusters.sh`
### Resources:
1. I refered to this [stackoverflow solution](https://gis.stackexchange.com/questions/319018/how-to-aggregate-other-columns-when-st-clusterintersecting-function-is-used)
2. Documentation for [ST_ClusterDBSCAN](https://postgis.net/docs/ST_ClusterDBSCAN.html)

**Comment by SPTKL** [comment]
Example logic on last year's table:
```sql
SELECT *,
         ST_ClusterDBSCAN(geom, 0, 1) OVER() AS _cluster_id
  FROM   kpdb_2020.combined
```

**Comment by mgraber** [comment]
After assigning cluster ID using ST_ClusterDBSCAN, will need to fill in NULLs with remaining integers.

**Comment by SPTKL** [comment]
incorporated
