### ISSUE TITLE
Remove inactive/test tables from build

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#153]
Only keep things referenced in code

**Comment by mgraber** [comment]
Should these be removed?
- [ ] combined_adtest
- [ ] dob_match_test
- [ ] dob_match
- [ ] dob_review_no_time
- [ ] sources
- [ ] clusters.fix
- [ ] clusters.test
- [ ] combined.combined_copy
- [ ] combined.fix
- [ ] combined.patch
- [ ] kpdb.2020_copy
- [ ] reviewed_clusters.2020_copy
- [ ] reviewed_clusters.fix
- [ ] reviewed_clusters.test
- [ ] reviewed_dob_match.2020_copy
- [ ] reviewed_dob_match.2020_mark (?)
- [ ] reviewed_dob_match.test

What are these and where do they get used?
- [ ] edc_dcp_inputs
- [ ] edc_sca_inputs

**Comment by SPTKL** [comment]
the edc_tables are not used anymore, Baoling created them to fill the missing geometries, now the geometries are filled in recipes, before they enter kpdb

**Comment by SPTKL** [comment]
for the tables with `_copy`, those tables cannot be recreated, so as long as we have a hard copy somewhere, in the database or as csvs, we can remove them

**Comment by mgraber** [comment]
Need to clarify (in docs) the difference between combined as a stand-alone table and and combined as a schema with versioned tables. What are the uses of each?
