### ISSUE TITLE
Issue with computation of units_net

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#154]
Seems to be an issue with counting DOB number of units
Example
project_id = 6-1
Units net should be 556.0 for the DOB job (it's currently NULL) and units_net should be 1719 for the DCP Planner-Added Projects record (it's currently 2275.0)

This pattern persists in records where the project id is 7-2, 8-2, 9-1

**Comment by SPTKL** [comment]
fixed 
32842e1b730d481eb3b43e1773b9117723823a1e
