### ISSUE TITLE
Need to take phasing proportions for DCP Planner-Added Projects

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#156]
Add the following into phasing.sql

```
-- DCP Planner-Added Projects
UPDATE kpdb."2020" a
SET   prop_within_5_years = b.portion_built_by_2025
     , prop_5_to_10_years = b.portion_built_by_2035
     , prop_after_10_years = b.portion_built_by_2055
     , phasing_known = 1
FROM dcp_planneradded_proj
WHERE a.source = 'DCP Planner-Added Projects'
AND a.record_id= b.record_id;
```

**Comment by mgraber** [comment]
Is this only for this year? Won't the years be incorrect for future updates?

**Comment by AmandaDoyle** [comment]
How would we get the phasing proportions for Planner-Added Projects in a future update?

**Comment by AmandaDoyle** [comment]
There may very well be a reason we left out the phasing for planner added projects that I'm not remembering

**Comment by SPTKL** [comment]
https://github.com/NYCPlanning/db-knownprojects/wiki/Planner-added-projects-table-schema
I think we will definitely have to change it in the future, not worth it to change the column names in this release tho

**Comment by SPTKL** [comment]
it makes sense to apply the phasing from last round of planner added projects, if anything needs to get updated, they would be captured in the new round of planner added projects

**Comment by SPTKL** [comment]
incorporated

0ff6fb5fb374689273fc16a25c799c8a340b6ad4
