### ISSUE TITLE
Finalize how Planner Added Projects will be corrected

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#158]
Will 1) all planner added projects be removed and then re-added 
or will 2) each row of the planner-added projects table be considered "locked" once it is added, and corrections will need to go into the manual corrections table.

DE proposed option 2

**Comment by AmandaDoyle** [comment]
Confirming, after meeting with @mshapiro1 @LubaPlanning
Going to move forward with option 2

**Comment by mshapiro1** [comment]
@AmandaDoyle  confirmed

**Comment by AmandaDoyle** [comment]
Updated documentation reflecting this
