### ISSUE TITLE
Fix DOB project IDs to apply corrections

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#183]
Corrections to DOB project IDs are not getting applied because the existing project_id no longer matches the old_value in the corrections file. Problem was likely created in #171. When creating stand-alone project IDs for unmatched DOB jobs, the order might be different depending on what stage the `units_gross <> 0` filter gets applied. Luckily, all of the rows in the corrections file where field = 'project_id' have either old_value or new_value matching the project_ids in kpdb_gross.2020 (with the exception of two autoformatted dates, which need a manual fix).  We can, for now, replace the project_ids in kpdb with those in kpdb_gross. Then the corrections will get applied. Going forward, this should not be an issue, since the logic for filtering the DOB jobs will be consistent for the whole run.

**Comment by mgraber** [comment]
Suggested fix:
Set project_ids in kpdb."2020" equal to the project_ids in kpdb_gross."2020", where they exist.
Rerun 05_corrections.

**Comment by SPTKL** [comment]
#182

**Comment by mgraber** [comment]
Fixed. kpdb.2020 is up to date as of May 26, 10:45AM.
