### ISSUE TITLE
When spatially joining DOB jobs to pluto use unclipped MapPLUTO

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#197]
Some DOB jobs are not getting a geomertry

**Comment by mgraber** [comment]
Should mappluto-derived geometries for other datasources also use the unclipped version?

**Comment by mgraber** [comment]
@AmandaDoyle Is this still the correct solution for the missing DOB geometries? Or is this an issue stemming from the version of housing DB?
