### ISSUE TITLE
2021 Input Data Inventory

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#206]
Input datasets:

### `dcp_knownprojects`: 
 - Take from recipes. **What version?**

### `esd_projects`:  
 - `2021.2.10 State Developments for Housing Pipeline.xlsx`
 - [x] extractor
 - [x] sql

### `dcp_n_study`
 - `2021.02.09 N'hood Study Rezoning Commitments.xlsx`
 - [x] extractor
 - [x] sql

### `dcp_n_study_future`: 
 - `2021.02.09 Future Rezonings.xlsx`
 - [x] extractor
 - [x] sql

### `dcp_n_study_projected`: 
 - `nstudy_rezoning_commitments_shapefile_20191008.zip`
 - [x] extractor
 - [ ] sql
 - [ ] @td928  this file is missing `effective_date`
 
### `hpd_rfp`: 
 - `2021.02.08 HPD RFPs.xlsx`
 - [x] extractor
 - [x] sql
> Previous version did not have geometry, we take geometries from BBLs [here](https://github.com/NYCPlanning/db-knownprojects/blob/9daa699bbd597a59c7653cc32c6dbf0d46ab293b/knownprojects_build/sql/hpd_rfp.sql#L22-L26).
> What is "hpd_rfps_shapefile_20191008.zip," and how should we incorporate it?**

### `hpd_pc`: 
 - `2021_2_18 DCP_SCA Pipeline.xlsx`
 - [x] extractor
 - [x] sql
 - NYCPlanning/db-knownprojects-data/pull/2

### `dcp_planneradded`: 
 - taking from last year
 - [x] extractor

### `dcp_housing`: #228 
 - taking 20Q4, waiting for DevDB to be published
 - [x] Loaded from pgdump using data libraries
 - [ ] sql 

### `edc_projects`： #214  NYCPlanning/db-knownprojects-data/pull/3
 - `2021.02.01 EDC inputs for DCP housing projections.xlsx`
 - edc_sca_inputs -> no longer used
 - edc_dcp_inputs -> use this instead
 - [x] extractor
 - [x] sql

### `dcp_rezoning`: 
 - "nyc_rezonings.zip" and/or "future_nstudy_shapefile_20191008.zip"  **It looks like the first contains the second**
 - [x] extractor
 - [x] sql

## Seperate process:
- [x] `dcp_mappluto`: Taken from recipes
- [x] `dcp_zoningmapamendments`: Taken from recipes
- [x] `dcp_boroboundaries_wi`: Taken from recipes

## ZAP Data #209
- [x] dcp_applications 
- [x] dcp_projects
- [x] dcp_projectactions

**Comment by td928** [comment]
Hi @mgraber, the edc file you mentioned should be archived version. I have moved it to the superceded folder. As for the willets point shapefile question, I believe it should be appended to the geometries in the other shapefiles since it is a new project and new geometry updated by EDC this time around. Thank you!

**Comment by mgraber** [comment]
@td928 it looks like the future_nstudy_shapefile_20191008 polygons are a subset of nyc_rezonings. Is this correct? Should we only be using nyc_rezonings?

**Comment by SPTKL** [comment]
@td928  KPDB data input will be stored here https://github.com/NYCPlanning/db-knownprojects-data

**Comment by td928** [comment]
> @td928 it looks like the future_nstudy_shapefile_20191008 polygons are a subset of nyc_rezonings. Is this correct? Should we only be using nyc_rezonings?


please use the nyc_rezonings for now. If we receive any update during our borough planner outreach process later, we will update the rezoning shapefile.

**Comment by SPTKL** [comment]
closing, data intake phase complete
