### ISSUE TITLE
Create/track unique IDs for each input data record

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#207]
## Goals
+ Maintain unique IDs (hash) for each record of input data in the input data repo
+ Link raw, record-level IDs to the unique IDs at the project level
+ Keep track of the number (and/or ID and content) of raw records that get rolled up to the project-level in the data-loading step

## Ideas

Use a json field to keep track of the various nesting IDs throughout the process.

At the step of data loading (`02_build_source_tables.sh`), this would only contain:
```
 "record_id": {
 // hash of the within-source project-level ID created during data-loading
     "raw_ids":{
               list of hashes of raw input data in a given record id
       }
```
Where there are more than one raw_id in cases where records have to get rolled up to the project level.

At the step of incorporating cluster review (First portion of `03.2_housing.sh`), this would contain:
```
{
 "project_id ": // ID formed by concatenation of cluster ID and reviewed subcluster ID,
     "record_ids ": {
        // hash of the within-source project-level ID created during data-loading
        "raw_ids":{
            // list of hashes of raw input data in a given record id
         }
    }
}
```

**Comment by SPTKL** [comment]
closing for now, this is relevant to current workflow
