### ISSUE TITLE
KPDB Wishlist 2022

### ISSUE THREAD

**Issue by kschmidtDCP** [NYCPlanning/db-knownprojects#212]
- [ ] Evaluate and revise logic around removing ZAP projects based on keyword search:  ( 'RESIDENTIAL TO COMMERCIAL',
  'SINGLE-FAMILY', 'SINGLE FAMILY',   '1-FAMILY', 'ONE FAMILY',  'ONE-FAMILY', '1 FAMILY',  'FLOATING', 'TRANSITIONAL', 
 FOSTER',  'ILLUMIN', 'RESIDENCE DISTRICT',  'LANDMARKS PRESERVATION COMMISSION',  'EXISTING HOME', 'EXISTING HOUSE',  'NUMBER OF BEDS', 'EATING AND DRINKING',  'NO INCREASE', 'ENLARGEMENT', 'NON-RESIDENTIAL',  'LIVINGSTON', 'AMBULATORY',  'APPLICATION FOR PARKING',  'CHAIRPERSON CERTIFICATION',  'ROOFTOP'], '|')

**Comment by SPTKL** [comment]
@kschmidtDCP  is this still relevant now that we have explicit add/removal for almost all projects?

**Comment by td928** [comment]
next enhancement items:

1. Adding community district to each project by spatial join centroid of project geometries
2. Boundary touching issues after new zap projects introduced 
3. Non hard code ZAP cutoff date

**Comment by td928** [comment]
Beyond enhancements, a few things that we are currently doing for KPDB that are 

- Neighborhood commitment files currently seems to have a major gap between 2019 and 2020 on. The file format has changed drastically and phasing assumption from the 2019 shapefiles are left out in the newer files. How to reconciliate those files and where the phasing assumptions will come from for the new projects?
-  similarly the development projects also have a series of DEP files are not yet incorporated into the workflows.

**Comment by td928** [comment]
Data Questions:

Currently the HPD RFP processing still uses a binary field "likely to be built by 2025".  Should this criteria be changed and how it would be change?
