### ISSUE TITLE
Allow process to run start-to-finish post-corrections

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#223]
# Brainstorming Issue
## Overview
**Goal**
Allow the whole process to run from start-to-finish, applying corrections in a predictable and reproducible way.

**Challenge**
Current process uses `cluster_id`, which isn't stable run-to-run.

**Solution**
Do not rely on `cluster_id`, and instead manipulate arrays of individual `record_id`s. This would require the following functionality.

### Identifying the matches
We will now do this using postgres, and not python. See #141.

### Produce a table for review
Need to scope out format

### Expected corrections file format
| record_id | action | record_id_match| 
|----------|-------|---------|
|          9    | reassign | 2 |
|           7    | reassign |     NULL    |
|          8    | combine  | 3 |

### Functions to apply corrections
Example of matched records:
| project_record_ids |
|------------|
| `{1,2,3,4}`  |
| `{5,6,7,8}`  |
| `{9,10,11}`  |

**Reassign**: removing a record from one group of matched records to another. 
For example,
| record_id | action | record_id_match| 
|----------|-------|---------|
|           7    | reassign |     2    |

should result in:
| project_record_ids|
|------------|
| `{1,2,3,4,7}`  |
| `{5,6,8}`  |
| `{9,10,11}`  |

This can also be used to separate out a record into a stand-alone project. 
For example,
| record_id | action | record_id_match| 
|----------|-------|---------|
|           7    | reassign |     NULL    |

should result in:
| project_record_ids |
|------------|
| `{1,2,3,4}`  |
| `{5,6,8}`  |
| `{9,10,11}`  |
| `{7}` |

**Combine**: Merging two, distinct groups of matched records. This means that they refer to the same project.
For example,
| record_id | action | record_id_match| 
|----------|-------|---------|
|           7    | combine |     2    |

should result in:
| project_record_ids |
|------------|
| `{1,2,3,4,5,6,7,8}`  |
| `{9,10,11}`  |

### Identifying the matches
This will now happen without relying on `cluster_id`. See #215

### Produce a table for review
Output of query in #215. Will contain all non-DOB records that matched with a DOB record. Flags will help reviewers focus on cases where a DOB record matched with more than one project. These need review.

### Expected corrections file format
| record_id | action | record_id_dob | 
|----------|-------|---------|
|           1    |  add  | 54321    | 
|           1    |  remove |  12345    | 

### Functions to apply corrections
Example matches
record_id | project_record_ids | record_id_dob 
---------- | ---------------- | -------
1 |  {1,2,3} | 12345 
2 | {1,2,3} | 12345 
3 | {1,2,3} | 12345 
4 | {4, 5} | 12345 
5 | {4, 5} | 12345 

**Remove a match**: A DOB record matched with a verified group of non-DOB records, but they are not referring to the same project.
For example,
| record_id | action | record_id_dob | 
|----------|-------|---------|
|           1    |  remove | 12345    | 

should result in:
record_id | project_record_ids | record_id_dob
----------| ---------------- | -------
4 | {4, 5} | 12345 
5 |  {4, 5} | 12345 

**Add a match**: A DOB record did not match with a verified group of non-DOB records, but it is actually referring to the same project.
For example,
| record_id | action | record_id_dob | 
|----------|-------|---------|
|           1    |  add | 54321    | 

should result in:
record_id | project_record_ids | record_id_dob
----------|  ---------------- | -------
1 |  {1,2,3} | 12345 
2 | {1,2,3} | 12345 
3 | {1,2,3} | 12345 
1 | {1,2,3} | 54321
2 | {1,2,3} | 54321
3 | {1,2,3} | 54321
4 |  {4, 5} | 12345 
5 | {4, 5} | 12345

**Comment by SPTKL** [comment]
What if we create a table that stores all clusters: 
*cluster_relations*
| cluster_id | record_ids |
|-----------|------------|
|                 1| `{1,2,3,4}`  |
|                 2| `{5,6,7,8}`  |
|                 3| `{9,10,11}`  |
Using the corrections file: 
1. removing a project from a cluster and add to another: (e.g. move record 7 from cluster 2 to cluster 1)

| record_id | action | neighbor| 
|----------|-------|---------|
|           7    | reassign |     2    |

Logic wise, we can use sql to remove record_id 7 from the array in cluster 2, and identify the cluster that contains the new neighbor cluster_id 2, and add record_id 7 to that cluster

Using this method, we are never using the cluster_id directly

**Comment by mgraber** [comment]
@SPTKL in the above example, are the values for `neighbor` cluster IDs, project IDs, or record IDs?

**Comment by mgraber** [comment]
Can we change `neighbor` to `match`?

**Comment by SPTKL** [comment]
## Reassign Example:
```sql
SELECT
	cluster_id, 
	array_agg(record_id) as record_ids
INTO cluster1
FROM(
	SELECT record_id, 
		coalesce(ST_ClusterDBSCAN(geom, 0, 1) OVER(), 99999) AS cluster_id
	FROM  combined
) a
group by cluster_id;



create table cluster1_corrections (
	record_id text,
	reason text,
	record_id_match text
);



SELECT 
	record_id,
	(
		select record_ids
		from cluster1 
		where record_id=any(record_ids)
	) as record_ids,
	(
		select record_ids
		from cluster1 
		where record_id_match=any(record_ids)
	) as new_record_ids
FROM cluster1_corrections WHERE
reason = 'reassign';


CREATE OR REPLACE PROCEDURE cluster1_reassign(
	record_id text, 
	record_id_match text
) AS $$
	UPDATE cluster1
	SET record_ids = array_remove(record_ids, record_id)
	WHERE record_id=any(record_ids);
	
	UPDATE cluster1
	SET record_ids = array_append(record_ids, record_id) 
	WHERE record_id_match=any(record_ids);
$$ LANGUAGE sql;

CALL cluster1_reassign('b5d2f06ccc4b0b06656f2277fe9140de', '85101');
```

**Comment by mgraber** [comment]
*Initial relationships*
| project_id | record_ids |
|-----------|------------|
| hash of (1, 2, 3, 4) | `{1,2,3,4}`  |
| hash of (5, 6, 7, 8) | `{5,6,7,8}`  |
| hash of (9, 10, 11) | `{9,10,11}`  |

Using the corrections file: 
## 1. *Reassign*: removing a project from a cluster and add to another: (e.g. move record 7 from cluster B to cluster A)

| record_id | action | match | 
|----------|-------|---------|
|           7    | reassign |     2    |

Result:
| project_id | record_ids |
|-----------|------------|
| hash of (1, 2, 3, 4, 7)  | `{1,2,3,4,7}`  |
| hash of (5, 6, 8) | `{5,6,8}`  |
| hash of (9, 10, 11) | `{9,10,11}`  |

Logic wise, we can use sql to remove project_id 7 from the array in cluster B, and identify the cluster (A) that contains the new neighbor project_id 2, and add project_id 7 to that cluster

Using this method, we are never using the cluster_id directly
## 2. *Combine*: combining two disconnected cluster: (e.g. connect cluster A with cluster B)

| project_id | action | match | 
|----------|-------|---------|
|           7    | combine_groups |     2    |

Result: 
| project_id | record_ids |
|-----------|------------|
| hash of (1, 2, 3, 4, 5, 6, 7, 8) | `{1,2,3,4,5,6,7,8}`  |
|  hash of (9, 10, 11) | `{9,10,11}`  |

logic wise, we will combine the two arrays of the two clusters containing these two record_ids, 7 and 2

**Comment by SPTKL** [comment]
### Combine 
```sql
CREATE OR REPLACE PROCEDURE cluster1_combine(
	record_id text, 
	record_id_match text
) AS $$
DECLARE

    new_record_ids text[];

BEGIN
	
	SELECT 
		array_agg(rid) AS record_ids
	INTO new_record_ids
	FROM (
		SELECT 1 as col, unnest(b.record_ids) as rid
		FROM cluster1 b 
		WHERE record_id = any(b.record_ids)
		OR record_id_match = any(b.record_ids)
	) a GROUP BY col;
	
	DELETE FROM cluster1
	WHERE record_id_match=any(record_ids);

	UPDATE cluster1
	SET record_ids = new_record_ids
	WHERE record_id = any(record_ids);
END
$$ LANGUAGE plpgsql;


CALL cluster1_combine('0efb2e50b0194ce6ff44ff0b73d59f18', '2020R0313');
```

**Comment by mgraber** [comment]
## Potential workflow for DOB match

record_id | cluster_id | cluster_id_input | dob_id
----------| --------- | ---------------- | -------
1 | A | {1,2,3} | 12345 
2 | A | {1,2,3} | 12345 
3 | A | {1,2,3} | 12345 
4 | B | {4, 5} | 12345 
5 | B | {4, 5} | 12345 


## 1. Remove DOB to cluster match, all others will remain
| record_id | dob_id | action | 
|----------|-------|---------|
|           1    |  12345    | remove |

**Result:**
record_id | cluster_id | cluster_id_input | dob_id
----------| --------- | ---------------- | -------
4 | B | {4, 5} | 12345 
5 | B | {4, 5} | 12345 


## 2. Add a DOB to cluster match (not something we did last time)
| record_id | dob_id | action | 
|----------|-------|---------|
|           1    |  54321    | add |

**Result:**
record_id | cluster_id | cluster_id_input | dob_id
----------| --------- | ---------------- | -------
1 | A | {1,2,3} | 12345 
2 | A | {1,2,3} | 12345 
3 | A | {1,2,3} | 12345 
1 | A | {1,2,3} | 54321
2 | A | {1,2,3} | 54321
3 | A | {1,2,3} | 54321
4 | B | {4, 5} | 12345 
5 | B | {4, 5} | 12345 

## 3. Make new, stand-alone clusters of DOB records 
**NOTE: this might only get called internally. It could be what we do at the end for non-matched records**
| record_id | dob_id | action | 
|----------|-------|---------|
|   NULL    |  67890    | new |

**Result:**
record_id | cluster_id | cluster_id_input | dob_id
----------| --------- | ---------------- | -------
1 | A | {1,2,3} | 12345 
2 | A | {1,2,3} | 12345 
3 | A | {1,2,3} | 12345 
4 | B | {4, 5} | 12345 
5 | B | {4, 5} | 12345 
67890 | C | {67890} | 67890

**Comment by mgraber** [comment]
## Procedure to apply round one corrections (WIP)

```sql

CREATE OR REPLACE PROCEDURE correct_projects () AS 
$$
BEGIN
<<reassign>>
FOR row IN (SELECT * FROM cluster1_corrections WHERE reason='reassign') LOOP
    CALL cluster1_reassign_null(row.record_id, row.record_id_match)
END LOOP reassign;

<<combine>>
FOR row IN (SELECT * FROM cluster1_corrections WHERE reason='combine') LOOP
    CALL cluster1_combine(row.record_id, row.record_id_match)
END LOOP combine;
$$ LANGUAGE plpgsql;
```

**Comment by AmandaDoyle** [comment]
Thinking about language and terms
- `record` describes individual rows (i.e. a record from HPD)
- `project` describes 2 or more records that are grouped together

In the examples of tables and workflow that may be shared with HED
- [ ] Replace instances of `cluster` with `project`
- [ ] change `reason` to `action` as the column name
- [ ] 

Question:
- In `3. New Cluster: Separate out records to form a cluster that doesn't yet exist` how would the first table option be created if needed?

**Comment by mgraber** [comment]
@AmandaDoyle I think part three would actually not be its own function. For an example of how we separate out previously-matched jobs to create stand-alone records, see the `With NULL option:` query I added to the round-one example [above](https://github.com/NYCPlanning/db-knownprojects/issues/223#issuecomment-786784252). I can update my brainstorming comment to reflect that.

**Comment by mgraber** [comment]
### Queries for incorporating DOB review

```sql
SELECT * 
INTO project_inputs FROM _project_inputs;
	
WITH 
dob_matches AS(
	SELECT DISTINCT
		record_id, 
		project_inputs
	FROM dob_review
	WHERE source = 'DOB'
),
matches_to_remove AS(
	SELECT 
		a.record_id, 
		a.project_inputs
	FROM dob_matches a
	JOIN dob_match_corrections b
	ON a.record_id = b.dob_id
	AND b.record_id = any(a.project_inputs)
	AND b.action = 'remove'
),
matches_to_add AS(
	SELECT 
		dob_id as record_id,
		record_id as record_id_match
	FROM dob_match_corrections
	WHERE action='add'
),
verified_matches AS (
	SELECT 
		record_id, 
		project_inputs[1] as record_id_match
	FROM dob_matches
	WHERE record_id||project_inputs::text
		NOT IN (SELECT record_id||project_inputs::text FROM matches_to_remove)
	UNION
	SELECT * FROM matches_to_add)
UPDATE project_inputs a
	SET project_inputs = array_append(a.project_inputs, b.record_id) 
	FROM verified_matches b
	WHERE b.record_id_match=any(a.project_inputs);

```

Then we need to add stand-alone projects. This would be both DOB and non-DOB.

```sql
INSERT INTO project_inputs
SELECT array_append(array[]::text[], record_id::text) as project_inputs
FROM dcp_housing_poly
WHERE record_id NOT IN (SELECT UNNEST(project_inputs) FROM project_inputs);

INSERT INTO project_inputs
SELECT array_append(array[]::text[], record_id::text) as project_inputs
FROM _combined
WHERE record_id NOT IN (SELECT UNNEST(project_inputs) FROM project_inputs);
```

**Comment by SPTKL** [comment]
everything up until this point is incorporated, we will close this issue for now
