### ISSUE TITLE
Incorporate corrections prior to clusters

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#227]
Workflow would be:
1. Load raw data
2. _sql/dcp_application to load ZAP data
3. _sql/dcp_housing to map columns of dob data
4. _sql/combine to put standardized input data into a single table
5. _sql/apply_corrections to correct input fields
    + Remove records (`field = 'remove'`)
    + Correct geometries (`field = 'geom'`)
    + Correct record_name (`field = 'record_name'`)
    + Correct borough (`field = 'borough'`)
    + Correct status (`field = 'status'`)
    + Correct type (`field = 'type'`)
    + Correct date (`field = 'date'`)
    + Correct date_type (`field = 'date_type'`)
    + Correct units_gross (`field = 'units_gross'`)
    + Correct prop_within_5_years (`field = 'prop_within_5_years'`)
    + Correct prop_5_to_10_years (`field = 'prop_5_to_10_years'`)
    + Correct prop_after_10_years (`field = 'prop_after_10_years'`)
    + Fill in phasing_rationale (`field = 'phasing_rationale'`)
    + Correct phasing_known (`field = 'phasing_known'`)
    + Correct boolean flags ( `field = 'nycha'`, `field = 'gq'`,  `field = 'senior_housing'`,  `field = 'assisted_living'`)
    + Correct inactive ( `field = 'inactive'`)
6. Make sure phasing proportions sum to 1

**Comment by SPTKL** [comment]
we might need to add a borough assignment statement in the end of the combined statement
```sql
CREATE OR REPLACE FUNCTION get_boro(
    _geom geometry
  ) 
    RETURNS varchar AS $$
      SELECT b.borocode::varchar
      FROM dcp_boroboundaries_wi b
      WHERE ST_Within(_geom, b.wkb_geometry)
  $$ LANGUAGE sql;
```

**Comment by mgraber** [comment]
Many of these corrections apply to dob, too, so we should add those records to the combined table.

**Comment by SPTKL** [comment]
#241
