### ISSUE TITLE
Update data-loading process

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#235]
## Source data
- [ ] ~~Run extractors (developed in #206) to load inputs from the db-knownprojects-data repo~~
- [x] Load data from data/processed NYCPlanning/db-knownprojects-data/pull/5
- [x] Load from recipes or data-library: dcp_knownprojects, dcp_mappluto, dcp_zoningmapamendments, dcp_boroboundaries_wi
- [x] Load ZAP data

## Corrections files
These might also live in the data repo, and get loaded via extractor
- [x] ~~project_inputs_corrections~~ -> corrections_project
- [x] ~~dob_match_review~~ -> corrections_dob
- [x] ~~kpdb_corrections~~ -> corrections_main

**Comment by SPTKL** [comment]
We will archive input tables by creating a pg_dump, and we will load directly from pg_dump instead of extractor

function output {
    pg_dump $BUILD_ENGINE -O -t $1 > processed/$1.sql
}

output esd_projects
output dcp_n_study
output dcp_n_study_future
output dcp_n_study_projected
output hpd_rfp
output hpd_pc
output dcp_planneradded
output edc_dcp_inputs
output dcp_rezoning

**Comment by mgraber** [comment]
When do the extractors get run?

**Comment by SPTKL** [comment]
> When do the extractors get run?

extractors will never get run, it's only created for us to iteratively load/inspect data, once we are sure everything is ok, we create the archived pg_dump, and will only load from pg_dump only

**Comment by SPTKL** [comment]
can we rename these tables, because I have no idea what they are

 project_inputs_corrections -> cluster 1?
 dob_match_review -> cluster 2?
 kpdb_corrections -> general corrections ?

**Comment by SPTKL** [comment]
incorporated #244
