### ISSUE TITLE
Post-deduplication build steps

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#252]
- [ ] Apply corrections where field = 'units_net', as in [`sql/correct_units_net.sql`](https://github.com/NYCPlanning/db-knownprojects/blob/dev/knownprojects_build/sql/correct_units_net.sql)
- [ ] Multiply phasing proportions with deduplicated units to get phasing counts, as in [`sql/phasing_counts.sql`](https://github.com/NYCPlanning/db-knownprojects/blob/dev/knownprojects_build/sql/phasing_counts.sql). This needs to happen after 'units_net' corrections

**Comment by SPTKL** [comment]
we can just do -> `psql $BUILD_ENGINE -1 -c "CALL apply_correction('_kpdb');"` to apply units_net corrections

**Comment by mgraber** [comment]
Yes, I was thinking we'd calculate the phased units during the join.
