### ISSUE TITLE
Proposed ZAP add / removal table

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-knownprojects#276]
@NYCPlanning/hed 
## ZAP add/removal table  - `corrections_zap.csv`
| record_id | action | date  | editor | notes |
| ---------  |  ------  | -----------  | -----   | ------ |
| PK12345  | add       | 2021/03/18 | HED | please include this record |
| PK12345  | remove | 2021/03/18 | HED | please do not this record |

```sql
CREATE TABLE corrections_zap (
    record_id text,
    action text,
    editor text,
    date text,
    notes text
);
```
## About this table
this table will be used to indicate for each ZAP record, if we need to add or remove that record from KPDB

**Comment by SPTKL** [comment]
Filter logic
If a project
1. satisfies year filter  -> and satisfies status filter -> add
2. satisfies units filter ->  and was marked as remove -> still add
3. satisfies add filter  -> add

**Comment by SPTKL** [comment]
I still think that add and remove from the corrections table should be the most authoritative indicator of if a record should be added or removed, because when an exception occur, there's no way we can overwrite that exception, unless we create a correction for a corrections file

**Comment by AmandaDoyle** [comment]
Hi all,
I'm synthesizing the above so I make sure I follow and agree.

Corrections_zap just captures ZAP records that should be added or removed in KPDB.  It does not capture value corrections that should be made to ZAP records.  Record_id should be unique in corrections_zap.

The logic for incorporating ZAP records into KPDB will be to
1) Add records that satisfy all 3 flags (flag_year=1 and flag_status=1 and flag_resid_units=1)
2) Add records that are an "add" in corrections_zap
3) Remove records that are a "remove" in corrections_zap
4) Flag records that are marked as "remove" but satisfy all 3 flags for HED to review and decide if they should be included in KPDB by removing the "remove" action from corrections_zap

If that's inline your understanding then we can move forward implementing this.

**Comment by kschmidtDCP** [comment]
I have a few changes to this logic, but want to verify with Sam and Te first. I'll try to have something by the end of the day!

**Comment by SPTKL** [comment]
@kschmidtDCP Just to clarify, do you mean: 
for records that are **not** in the add/remove list, if they satisfy `flag_year=1` and `flag_status=1` but `flag_resid_units=0`, still flag as a **add**. 

So basically, for all records **not** in the add/remove list, add if  `flag_year=1` and `flag_status=1`, regardless `flag_resid_units=1 or 0`

**Comment by kschmidtDCP** [comment]
> for records that are **not** in the add/remove list, if they satisfy `flag_year=1` and `flag_status=1` but `flag_resid_units=0`, still flag as a **add**.
> 
> So basically, for all records **not** in the add/remove list, add if `flag_year=1` and `flag_status=1`, regardless `flag_resid_units=1 or 0`
 
Yes, this is correct,

**Comment by SPTKL** [comment]
https://github.com/NYCPlanning/db-knownprojects-data/pull/18
