### ISSUE TITLE
Phase 1 Project Review Feedbacks

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-knownprojects#286]
# To-do:
- [ ] fill in BBL for HPD rfp projects where bbl is missing and reupload file to raw folder

1. There are 129 records where the data is not populated except the source data field is filled with a long strings. 
2. There's an HPD project "NYCHA Seniors First: Kingsborough and Morris Houses RFP" that needs to be split into two different records. We can do this directly in the HPD input table, or find a way to handle it in the corrections table.
3. An HPD RFP "9a6f4817402c03f082317d7f72a0c132", "Former PS90 RFQ", should have been geocoded with the BBL in the HPD input table (3051030058). This BBL in is PLUTO.

**Comment by mgraber** [comment]
> An HPD RFP "9a6f4817402c03f082317d7f72a0c132", "Former PS90 RFQ", should have been geocoded with the BBL in the HPD input table (3051030058). This BBL in is PLUTO.
Our current code uses the BBL field to join with PLUTO. There are multiple records in the HPD_RFP input data that have boro, block, and lot, but do not have BBL filled in. We will either have to:
1) Correct source data
2) Backfill BBL
3) Use the other three fields to perform a join

Also worth noting that there is 'p/o' in the lot value for the record with name Stapleton Site A RFP.

**Comment by mgraber** [comment]
> There are 129 records where the data is not populated except the source data field is filled with a long strings

This is probably because we're exporting CSVs with geometry columns. The shapefile should be fine. We'll modify our export step to exclude geometries from the CSV version of these tables.

**Comment by SPTKL** [comment]
> 4. P2014Q0293 has a valid BBL in ZAP, but isn't being geocoded (4115620113)

in PLUTO 20v1, this lot is now part of a bigger lot
![image](https://user-images.githubusercontent.com/13207770/112531898-86afdc80-8d7e-11eb-855e-c9b41841f4c7.png)

current geometry (20v8) in zola
![image](https://user-images.githubusercontent.com/13207770/112531917-8fa0ae00-8d7e-11eb-8cd6-6565001cc4e8.png)
