### ISSUE TITLE
DOB cluster intersection matching

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-knownprojects#33]
## Logic: 
1. Match dob jobs with each source table with the following constraints: 
    a. source project year -1 < dob job year
    b. spatial intersection
2. For each dob job, identify cluster_id and sub_cluster_id
    a. if dob job matches with multiple cluster_id, sub_cluster_id combinations --> flag for review
    b. else pass

## Proposed query (on going ...)
```sql
-- this part represents the dob jobs that would definitely need review
with cluster_intersections as (
	select distinct st_intersection(a.geom, b.geom) as geom, a.cluster_id, a.sub_cluster_id,
	split_part(split_part(a.date, '/', 1), '-', 1) as year_a,
	split_part(split_part(b.date, '/', 1), '-', 1) as year_b
	from clusters."test" a, clusters."test" b
	where a.geom > b.geom
	and a.cluster_id = b.cluster_id
         and a.sub_cluster_id = b.sub_cluster_id)
	select a.cluster_id, a.sub_cluster_id, b.job_number, a.geom as geom_a, b.geom as geom_b
	from cluster_intersections a, dcp_housing b
	where st_intersects(a.geom, b.geom)
	and least(a.year_a::numeric, a.year_b::numeric) < extract(year from b.date::timestamp)
```

**Comment by SPTKL** [comment]
![Untitled drawing](https://user-images.githubusercontent.com/13207770/78682783-71674700-78bc-11ea-85d0-f675193f4e1f.jpg)

**Comment by mgraber** [comment]
Basically. Some caveats:
- We should extract both red boxes, with the "needs review" as a subset. 
- There is one more step of filtering. For this record to need review, Project from source A and Project from source B would have to be in different verified clusters. I see two ways of doing this. We could just check the cluster/sub IDs and only include in the "needs review" subset if the yellow box's cluster/sub ID doesn't equal the blue box's ID (probably the best approach), or we could create a cluster-level geometry by running ST_union on everything sharing a cluster/sub-cluster_id prior to running the intersection query.
- There is potentially a time component in determining whether these things overlap, not just a spatial component.
