### ISSUE TITLE
hpd_rfp -- HPD RFPs

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-knownprojects#4]
#### dataset alias: hpd_rfp
- [x] dataloading
- [x] geocoding
    1. Extract addresses from project names,
- [ ] deduplication

**Comment by baolingz** [comment]
We received another dataset from Capital Planning, which was created by HPD.

Things to confirmed:
- which source data should we use? hpd_rfp or hpd_rfps_1 (having bbl and geometries)?
- In hpd_rfps_1, what does `the_geom` stands for?
- In KPDB_Tracker.xlsx, some permits are associated with multiple bbls, which is not the case in hpd_rfps_1, which one is more up-to-date?

**Comment by mshapiro1** [comment]
@baolingz responses to each bullet are in the corresponding bullets below

- hpd_rfp should be used as source data, but you should join on BBL from hpd_rfps_1. the key to do so is in the code below. happy to chat about this further! 

`		
on 
			(a.rfp_project_name = b.rq__p_n) 																										or 
			(a.rfp_project_name = 'NYCHA Twin Park West'										and b.bbl in (2031430234,2031430236,2031430240)) 	or 
			(a.rfp_project_name = 'MWBE Site D - 359 E. 157th Street / 784 Courtlandt Avenue' 	and b.bbl in(2024040001, 2024040002)) 				or 
			(a.rfp_project_name = 'NYCHA Betances V' 											and b.bbl in(2022870026, 2022870071)) 				or
			(a.rfp_project_name = 'NYCHA Betances VI'											and b.bbl =2022910001)								or
			(a.rfp_project_name = 'Broadway Triangle'											and upper(b.rq__p_n) like '%BROADWAY TRIANGLE%')
`

- You will see the_geom in a few of the input datasets. It is CartoDB's field which holds point/polygon location data. 

- let's talk about this in today's meeting.

**Comment by SPTKL** [comment]
```sql
with s0_consolidate_rfp as (
	select a.bbl, b.*, nullif(b.announced_unit_count, '-') as total_units
	FROM hpd_rfp_bbl a, hpd_rfp b
	WHERE a.project_name = b.project_name
	), s1_match_project as (
		select a.bbl, a.project_name, b.project_id as zap_id
		from s0_consolidate_rfp a
		left join zap_bbl b
		on a.bbl = b.bbl
	), s2_pair_zap as (
		select project_name, zap_id from(
			select project_name, zap_id,
			ROW_NUMBER() OVER(PARTITION BY project_name ORDER BY num DESC) AS row_number 
			from (
				select project_name, left(replace(zap_id, 'P', ''), 4)::numeric+right(zap_id, 4)::numeric as num, zap_id
				from s1_match_project) a
		) b WHERE row_number=1
	), s3_format as (
		SELECT a.bbl, a.project_name, 
		a.total_units, b.zap_id, 
		(case when b.zap_id is null then a.project_name||'-hpd_rfp'
		 else b.zap_id end) as project_id
		FROM s0_consolidate_rfp a
		LEFT JOIN s2_pair_zap b
		ON a.project_name = b.project_name
	), s4_get_zap_units as (
		select a.*, b.new_dwelling_units as zap_units
		from s3_format a
		LEFT JOIN dcp_application b
		ON a.zap_id = b.project_id
	), s5_get_planner_units as (
		select a.*, b.total_units_from_planner as planner_units
		from s4_get_zap_units a
		left join planner_inputs b
		on a.zap_id = b.project_id
	) select * from s5_get_planner_units;
```
