### ISSUE TITLE
Include all jobs that are in housing DB in final KPDB

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#57]
Include inactive jobs
Withdrawn jobs is still up to question

**Comment by mgraber** [comment]
- [ ] Loosen the filters in dcp_housing.sql: currently we are removing jobs that are demolitions, jobs that are withdrawn, and jobs with negative proposed units

- [ ] After ingesting the dob-review table, update the dcp_housing_proj table with development_id. For records that have NULL id, generate development_id

**Comment by LubaPlanning** [comment]
Seems I can't add a label, but this issue is also awaiting HED input.

**Comment by AmandaDoyle** [comment]
this might be impacted by issue #84

**Comment by LubaPlanning** [comment]
Agreed to include all jobs except jobs with 0 units. I believe no additional CP or HED input is needed here.
