### ISSUE TITLE
dcp_applications -- DCP applications

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-knownprojects#6]
#### dataset alias: dcp_applications
- [x] dataloading
- [x] geocoding
    1. Extract addresses from project names
- [ ] deduplication 

#### filter: 
- there are a lot of projects from the 70s, need to remove, what is the cut off --> 2012 confirmed with mark (except hudson yards n etc)
- how to remove living quarters, senior housing & etc (none housing related projects) --> see https://github.com/NYCPlanning/Known-Projects-Database/blob/master/1d_(v).%20New_Relevant_Projects_DCP_Flagging.sql --> manually tweaked
- filter by anticipated year built?

**Comment by mshapiro1** [comment]
@baolingz there's a process to geocoding these DCP projects that includes matching with the previous round of shapefiles. we'll talk about this at today's meeting!

**Comment by mgraber** [comment]
Alter to backfill from previous year if it exists, else use geosupport to get BBL-level polygon geometry

**Comment by SPTKL** [comment]
UPDATE dcp_application a
SET wkb_geometry = ST_MakeValid(b.wkb_geometry)
FROM (
	select project_id, ST_Union(ST_MakeValid(wkb_geometry)) as wkb_geometry 
	from zap_bbl_geom 
	group by project_id)b
WHERE a.project_id = b.project_id;
