### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#60]
Take the ID from the following sources
DOB: job number
ZAP: ZAP ID
HPD Projected Closing: Project ID/Building ID
Generating an ID for all other sources

Need to decide ID for N. Study Rezoning Commitments
Proposal: Include neighborhood study name as prefix in the project name, and generate ID
CP wants to include the neighborhood study name in the ID

**Comment by LubaPlanning** [comment]
Please let me know if you need additional input from us or HED on this. Have not asked HED for input.

**Comment by AmandaDoyle** [comment]
@LubaPlanning 
We need consensus on what the ID should be that come from N. Study Rezoning Commitments
See what we propose above, which is different than what CP has requested

**Comment by LubaPlanning** [comment]
Ah, I mis-read your first comment and thought that you were suggesting to have the study name as a prefix in the ID, then generate the rest of the ID.

Ideally, we don't want to change the project name so that it's easier to visually compare projects that have similar names. But we still want to be able to sort the final database based on the rezoning. Could you help me understand why you'd rather not use the rezoning name in the ID?

**Comment by AmandaDoyle** [comment]
@LubaPlanning can you explain how having
Jerome: Project Name
hinders the ability to visually compare project name? 
It enables you to just use the project name field to sort projects part of the same rezoning and have project names then stack in alphabetical order.
Adding in the rezoning name as a prefix to the ID
1) breaks the uniformity across record ID
2) The ID should not be used to sort and filter projects based on an attribute

**Comment by SPTKL** [comment]
Conclusion: 
OK to Append id to name

**Comment by AmandaDoyle** [comment]
I'm unclear as to what the conclusion is
is it study name + ID in the ID column?  Or are we leaving the ID as a hash and doing study name + project name in the project name column?

**Comment by LubaPlanning** [comment]
Record ID = hash 
Name = Study Name + name

If there's a way to add a character between study name and project name for the concatenated Name field, that would be great. Whatever special character (: | - or anything else) won't mess with your code would work!

**Comment by mgraber** [comment]
To-do:
- [ ] Rename `project_id` as `record_id`
- [ ] Rename `project_name` as `record_name`
- [ ] Set `record_id` as hash in dcp_n_study.sql
- [ ] Set `record_id` as hash in dcp_n_study_projected.sql (?)
- [ ] Set `record_id` as hash in dcp_n_study_future.sql (?)
- [ ] Set `record_id` as hash in edc_projects.sql
- [ ] Set `record_id` as hash in esd_projects.sql
- [ ] Set `record_id` as hash in hpd_rfp.sql
- [ ] Set `record_name` as `neighborhood_study || - || commitment_site` in dcp_n_study.sql
