### ISSUE TITLE
KPDB source-specific tables

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#61]
What are the source specific tables

**Comment by LubaPlanning** [comment]
In the original documentation Mark provided for you, the KPDB has the main tab, and then a "source-specific table" tab for each of the input data sets that shows additional information available for those sources. It is basically a separate tab for each input data set. I'd like to revisit as a group whether we should create these again - I'll add it to the agenda for the next KPDB meeting.

**Comment by AmandaDoyle** [comment]
@LubaPlanning LubaPlanning flagging for you since this was not covered

**Comment by LubaPlanning** [comment]
@AmandaDoyle didn't prioritize this as it would be for the final KPDB, not for planner review. Will discuss with HED before May 11th - let me know if that timeframe works.

**Comment by AmandaDoyle** [comment]
@LubaPlanning that's fine with me
