### ISSUE TITLE
Matching DOB jobs to other records methodology

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#64]
Finalize matching methodology.  

- [x] Need to decide we leave as is w/ just spatial match or include fuzzy name matching - confirmed want fuzzy matching
- [x] Include inactive jobs in the DOB matching process - confirmed, yes
- [x] ~~need to confirm that the date filed date it the correct DOB date to use when comparing to years of other projects - confirmed, date filed is correct?~~

**Comment by AmandaDoyle** [comment]
Action items:
- [ ] First match spatially, then match using fuzzy string matching by comparing addresses / project names
- [ ] Add in inactive jobs to subset of DOB jobs that are being included in matching process.  Are inactive jobs excluded from Housing DB?  If so, this will be a broader conversation of including inactive DOB jobs in Housing DB

**Comment by mgraber** [comment]
Fuzzy string matching should occur in dob_match.sql. We create `matches`, which is an inner join between DOB and non-DOB on spatial intersection. Also find the inner join of DOB and non-DOB on `address` similar to `project_name`. Create a union of these two types of matches before the union with non-DOB attributes contained in `combined`.

**Comment by mgraber** [comment]
After exploration of the data, we do not recommend implementing fuzzy string matching (i.e. levenshtein distance, trigrams, phoenetic matches). These techniques aren't well-suited to handle addresses, where differences of a single digit are significant. For example, 116 Broadway and 16 Broadway are very different places, but would match with a fuzzy string matching algorithm even at a very high similarity threshold.

Similarly, an explicit string comparison like the one included in last year's workflow (see below), does not provide a big improvement over spatial matches. For the 2020 data, a strictly spatial approach finds 914 matches between a DOB record and a non-DOB record. Including the following string comparison finds only an additional two matches, or 916 total.

```sql
position(upper(b.project_name) in upper(a.project_name)) > 0 and
					case when position('-' in a.project_name) = 0 then left(upper(a.project_name),5) = left(upper(b.project_name),5) END
```

**Comment by AmandaDoyle** [comment]
Confirmed we will not use fuzzy string matching
#82 covers the change to the data constraint
