### ISSUE TITLE
Implement phasing assumptions

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#67]
1) need to receive phasing assumptions

**Comment by LubaPlanning** [comment]
All phasing agreed upon with HED and CP in column "Proposed Phasing 2020" in this spreadsheet:
https://nyco365.sharepoint.com/:x:/s/NYCPLANNING/cp/EbwM5Y6-U8dDu6K2CUdC4KMB3VKCI-l85c1n9mvklHObcQ?e=odR8Lh

**Comment by AmandaDoyle** [comment]
@LubaPlanning going back to the buckets outlined in the [table schemas](https://github.com/NYCPlanning/db-knownprojects/wiki/KPDB-Schema)
Can we get confirmation that the phasing assumption buckets should be 
- Units built within 5 years
- Units built within 5-10 years
- Units built after 10 years

**Comment by LubaPlanning** [comment]
Confirmed!

**Comment by AmandaDoyle** [comment]
@LubaPlanning @mshapiro1 @levysamu @
We need some clarification around some of the phasing assumptions

- [ ] HPD Projected Closings: 2.5 years after financing close.  The only date field in the source data is the projected fiscal year range.  What exactly is the logic for HPD Projected Closings?

- [ ] EDC: EDC-provided build year I want to confirm the following logic
- If the build year is equal to or 5 years greater than the current year then it's completed within next 5 years (so for the 2020 version, records with a build year between 2020 and 2025 are completed within the next 5 years, but for the 2021 version this would be between 2021 and 2026)
- This would then cascade to fill in the other phasing buckets
- Records with a build year less than the current year (i.e. 2019) are assigned no phasing

- [ ] Confirming that all ZAP records / DCP applications where the Status <> Record Closed get put into the 5 - 10 year bucket

- [ ] Empire State Development Projects: Confirming that we don't build any logic for this and the phasing values will come from the manual input table

- [ ] Neighborhood Study Rezoning Commitments - it's probably worth having a call to discuss this because it is not clear how we get this information from EDC.  Will planner inputs come from via the manual corrections table.  Is 2025 a hard coded date?

- [ ] Neighborhood Study Projected Development Sites: I don't see a estimated buildout timeline in the source data.  Can you explain what your referring to here?

- [ ] Future Neighborhood Studies: Should we just use the buld_period value?

**Comment by mshapiro1** [comment]
@AmandaDoyle responses and requests for HED input are below:

HPD Projected Closings (@levysamu input needed): HPD provides us info on when they expect a project to close financing. Last year, we assumed that a DOB permit would be issued immediately after financing, and it would take 2.5 years from permit issued to project completion. Are you comfortable with this assumption this year, or should we increase from 2.5 years?

EDC: First two bullets confirmed. For the third bullet, if a project is not completely materialized but shows a "build year" before the current year, we should put it in the 0-5 years bucket.

ZAP: confirmed

Empire State Development Projects: confirmed

N. Study Rezoning Commitments (@levysamu and @LubaPlanning input needed): EDC manually provided us info on DTFR and Inwood in a spreadsheet, and we then manually inputted this info. This year, we can manually input information using the manual corrections table. We'll look for updates for the DTFR and Inwood projects, as well as other rezoning commitments, through planner input.

N. Study Projected Development Sites: Will provide additional info after call with T. Smith today

Future N. Studies: Will provide additional info after call with T. Smith today

**Comment by levysamu** [comment]
For the HPD projects, assuming that HPD projects move at the same speed at DoB as all other projects, we would typically say 3-4 years. Do you have a sense that these projects move faster, @mshapiro1 ?

**Comment by mshapiro1** [comment]
@levysamu I don't know why these projects would move differently than other DOB projects. Do we want to say we expect completion 3 years after the financing is closed?

**Comment by levysamu** [comment]
I think that makes sense.

**Comment by mshapiro1** [comment]
we have @LubaPlanning signoff as well

**Comment by mshapiro1** [comment]
Record of meeting with T. Smith, @AmandaDoyle , and HED (@levysamu). We have N. Studies, EDM, HED, and CP signoff on the below.

Phasing:

1. Neighborhood Study Projected Development Sites: Development begins 3 years after the "effective date", and progresses linearly through the build period until reaching the total unit count. All of these studies have 10-year build period after the "effective date", except for East New York, which has a 15-year build period.
2. Future N. Studies: All studies with 10-year build except for Gowanus, with 15-year build period. If 10-year build period, then 50% of unit phased 5-10 years, and 50% of units phased 10+ years. If 15-year build period, then 1/3 of units phased 5-10 years, and 2/3 phased 10+ years.

Also, as Capital Planning receives updates from the N. Studies team on neighborhood studies in mid-May, they will update the unit counts and phasing in the manual corrections table.

**Comment by mshapiro1** [comment]
@AmandaDoyle 

"Follow-up question: @mshapiro1 - are we confirmed that the phasing for these projects will come from the manual corrections table?"
**Yes**

"Follow-up question: @mshapiro1 - I don't know how to interpret the answer as it relates to the how we allocate the percentage of units to each of the three phasing buckets. There is no "effective date" field. In the collapses project table, I do se protion_built_by_2025, 2035, 2055. Should we used these values?"

**Apologies, it seems "effective date" is not in the shapefiles I provided. It's available in the source-specific sheet of the KPDB Excel doc and below. All of the rezonings in this source have 10-year build period, except for ENY with a 15-year build period. A project with a 10-year build period can have completions beginning 3 years after the effective date and should have all of its units completed 10 years after the effective date. If we distribute units evenly across that 7 year period, that means that 100%/7 units would be phased each year. Let me know if a call to discuss this would be helpful**


Neighborhood | Effective   Date
-- | --
Bay Street Corridor | 7/1/2019
Downtown Far Rockaway | 9/7/2017
East Harlem | 11/30/2017
East New York | 4/20/2016
Inwood | 3/22/2018
Jerome | 1/16/2018

"Follow-up: Okay. I recommend adding a field to the source data input that indicates what the build period is for each project"

**Sounds good. Let us know where we can modify this source data**

**Comment by mshapiro1** [comment]
cc: @AmandaDoyle 

@levysamu looking for your confirmation

"Follow-up question: @mshapiro1 @levysamu the only date field in the source data is the projected fiscal year range. How does the proposed logic work when there is no "financing closed" date, but with the projected fiscal year range?"

**For phasing purposes, let's assume that the "financing closed date" is December 31st of the last year in the projected fiscal year range** 

"Follow-up question: how do you know if a project has completely materialized or not?"

**I'll rephrase this! If a project's build year is before the current year, phase all remaining units after deduplication in the 0-5 year bucket**

**Comment by levysamu** [comment]
@mshapiro1 

I think I'm fine with what you outlined above, although I am also not 100% sure I understand it.

**Comment by AmandaDoyle** [comment]
@SPTKL @mgraber 
If you'd like to pick this up, I'm stuck on the logic for Neighborhood Study Projected Development Sites

I didn't know where we landed on naming so the field names and table name will need to be updated.

Lastly, the KPDB table should have 6 phasing fields (portion and count).  The phasing assumptions will assign the portion, and then in the end we'll compute the count.  We'll only output the phasing count fields in the final export

**Comment by mgraber** [comment]
There is a kpdb_gross and a kpdb. We can switch from the 6 fields to the 3 fields using those two tables.

**Comment by mgraber** [comment]
Because n_study_future and n_study_projected do not go through the same unit subtraction process as the other sources, I would recommend implementing the phasing logic for these records when they get appended to kpdb, rather than when records get dumped into kpdb_gross.

See #119.
