### ISSUE TITLE
Agree on planner review process for all sources

### ISSUE THREAD

**Issue by LubaPlanning** [NYCPlanning/db-knownprojects#68]
@AmandaDoyle - can you clarify the current process for the planner-added projects table and the planner review? My understanding is the following:
1. EDM outputs planner-added projects from the previous year into the planner-added projects table. We review with planners and, fixing projects on the list and adding additional projects. The updated table replaces the old table as an input into KPDB.
2. All other sources (Except ZAP)- we review the entire KPDB output (since you are not producing any sub-tables) and use the manual corrections table to update info for all other sources.
3. ZAP - We expect to be making a lot of corrections to ZAP records. Initially we were going to tell planners to simply update ZAP, but it looks like that won't be possible. Is there a way for us to batch update ZAP records, rather than using the manual corrections table? This process is much more similar to planner review of planner-added projects than to their review of DOB or other sources.

**Comment by SPTKL** [comment]
the current __planner added projects__ is provided by @mshapiro1

**Comment by AmandaDoyle** [comment]
@LubaPlanning 
1. Correct.  @mshapiro1 is providing this table as input
2. Yes
3. Let's discuss with CP and HED.  We'd like to minimize the number of different inputs.  We'd need to rationalize why the manual corrections table won't work and if we don't use it will that be okay (i.e. is not tracking the old value before overwriting a value important?)

**Comment by LubaPlanning** [comment]
A couple of items:
1. I want to make sure we are aligned on the format of the planner-added input table, since we have discussed some changes during our nomenclature meetings. Adding this to the agenda for Tuesday.

3. I agree that this warrants discussion. I'll add this to the agenda for Tuesday.

**Comment by LubaPlanning** [comment]
Agreed via meetings last week and email April 23rd that:
1. CP and HED gave final input on planner-added project schema
2. Manual Corrections table
3. Will use a spreadsheet for ZAP, then transform to format of manual corrections table for input into KPDB process

**Comment by mgraber** [comment]
#62
