### ISSUE TITLE
Reviewers adding ZAP projects

### ISSUE THREAD

**Issue by LubaPlanning** [NYCPlanning/db-knownprojects#69]
Need to determine how reviewers will add projects that should be present from ZAP but weren't caught in the filter and are not yet in the manual table - do we add this to EDM's ZAP manual research table? If so, how?

**Comment by SPTKL** [comment]
Yes, this should be added to the manual research table. The manual research table can be used through out the build steps for different purposes. In this case, we can add/remove ZAP projects from the manual research table right after the ZAP filtering takes place. 

The build process is iterative, we go through

`build` ==> review, produce `manual research` ==> `build` again with fresh manual research ==> review, add to previous `manual research` (if needed) ==> `build`.... 

till we have satisfactory result

**Comment by LubaPlanning** [comment]
Great. Please advise on the right inputs to add ZAP projects to the manual research table so they pull in from ZAP during the subsequent build phase.

**Comment by SPTKL** [comment]
Based on agreed upon manual research schema: 
to remove a project from ZAP:
project id | field | old value | new value | editor | date | Project Name | Notes
-- | -- | -- | -- | -- | -- | -- | --
PK201932| remove | | | | baiyue| 4/20/2020| | some comments

To add a project: 
project id | field | old value | new value | editor | date | Project Name | Notes
-- | -- | -- | -- | -- | -- | -- | --
PK20302| add | | | | baiyue| 4/20/2020| | some comments

**Comment by LubaPlanning** [comment]
Perfect. Thanks!

**Comment by mgraber** [comment]
#62
