### ISSUE TITLE
Add date fields to project-level table

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#7]
**Project-level tables need date fields, so that these can be included in the cluster verification process. These are the date fields available in the source data.**

Data sources in first-round cluster evaluation:
- **1) `dcp_application`**: `dcp_projectcompleted`, **`dcp_certifiedreferred`**
- **0)`esd_projects`**: No date fields
- **4)`edc_projects`**: `build_year`
- **0)`dcp_n_study`**: No date fields
- **2) `hpd_rfp`**: `closed_date`
- **3) `hpd_pc`**: `projected_fiscal_year_range`

Second round cluster verification:
- **`dcp_housing`**: `complete_year`, `permit_year`, `date_filed`, `date_statusd`, `date_statusp`, `date_permittd`, `date_statusr`, `date_statusx`, `date_lastupdt`, `date_complete`

Other:
- **`dcp_n_study_future`**: `effective_year`
- **`dcp_n_study_projected`**: No date fields

Note that the schema needs to be consistent between project-level tables. There will likely be many columns with all NULL.
***

Proposed schema additions:
- **`date`**, not null for: dcp_application (`dcp_certifiedreferred`), 
                                            edc_projects (`build_year`),
                                            dcp_n_study_future (`effective_year`), 
                                            hpd_pc (`projected_fiscal_year_range`), 
                                            hpd_rfp (`closed_date`)
- **`dcp_projectcompleted`**: not null for dcp_application
- **`complete_year`**: not null for: dcp_housing
- **`permit_year`**: not null for: dcp_housing
- **`date_filed`** : not null for: dcp_housing
-  **`date_statusd`** : not null for: dcp_housing
-  **`date_statusp`** : not null for: dcp_housing
- **`date_permittd`** : not null for: dcp_housing
-  **`date_statusr`** : not null for: dcp_housing
- **`date_statusx`** : not null for: dcp_housing
-  **`date_lastupdt`** : not null for: dcp_housing
- **`date_complete`**: not null for: dcp_housing

**Comment by mgraber** [comment]
**Modifications to table definition:**
A column only needs to be added if it isn't already in source data by the same name.

```
    ADD date_projected text,
    ADD date_closed text,
    ADD date_complete text,
    ADD date_filed text,
    ADD date_statusd text,
    ADD date_statusp text,
    ADD date_permittd text,
    ADD date_statusr text,
    ADD date_statusx text,
    ADD date_lastupdt text,
```

**Updated column selection for geometry merging:**

```
SELECT b.source, b.project_id, b.project_name,
    b.project_status, b.project_type, b.inactive,
    b.number_of_units, b.date_projected, b.date_closed,
    b.date_complete, b.date_filed, b.date_statusd,
    b.date_statusp, b.date_permittd, b.date_statusr,
    b.date_statusx, b.date_lastupdt, b.portion_built_by_2025,
    b.portion_built_by_2035, b.portion_built_by_2055,
    a.geom
```

**Comment by mgraber** [comment]
#9 #8

**Comment by SPTKL** [comment]
all possible date fields from dcp_project (zap)
```
createdon
modifiedon
overriddencreatedon
dcp_applicationfiled
dcp_cemplannedcompletiondate
dcp_certificationtargetdate
dcp_certifiedreferred
dcp_cmplannedcompletiondate
dcp_cpcdeadlinestartedon
dcp_cpcdeadlinestoppedon
dcp_dcptargetcertificationdate
dcp_isplannedpostcertenddateoverridden
dcp_isplannedpostcertenddateoverriddenname
dcp_ispostcertstartdateoverridden
dcp_ispostcertstartdateoverriddenname
dcp_isprecertstartdateoverridden
dcp_isprecertstartdateoverriddenname
dcp_istargetcertificationdateoverridden
dcp_istargetcertificationdateoverriddenname
dcp_lastmilestonedate
dcp_migratedceqrlastupdateddate
dcp_migratedlastupdateddate
dcp_plannedpostcertenddate
dcp_postcertstartdate
dcp_precertstartdate
dcp_projectcompleted
dcp_projectstagedate
dcp_projectstatusdate
dcp_statusdate
dcp_targetcertenddate
lastonholdtime
dcp_daysonhold_date
dcp_validatedcommunitydistricts
dcp_cpcdeadlinedate
dcp_totalprecertonholddays_date
dcp_publicvisibilitydate
dcp_ulurpearliestpossiblecertificationdate
```
our filter is using
```
SELECT dcp_projectid,dcp_name, dcp_projectcompleted,dcp_certifiedreferred,dcp_residentialsqft,statuscode,dcp_applicanttype,
				dcp_projectbrief, dcp_projectdescription, dcp_projectname, dcp_borough, dcp_numberofnewdwellingunits
		FROM dcp_project
		WHERE  (dcp_name ~* 'P2005M0053|P2009M0294|P2014M0257' or dcp_name !~* 'P2016Q0238|P2016R0149|P2012M0255')
		AND (extract(year from dcp_projectcompleted) >= 2012 or extract(year from dcp_certifiedreferred) >= 2012)
```

**Comment by mgraber** [comment]
For **`dcp_housing`**, remove `complete_year`, `permit_year` because they are redundant with `date_permittd` and `date_complete`.

Also remove `date_statusd`, `date_statusp`, `date_statusr`, `date_statusx`

Standardized sort date field will have `date_filed`
