### ISSUE TITLE
n_study  -- Neighborhood study rezoning commitments

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-knownprojects#8]
"n_study"

**Comment by baolingz** [comment]
@mshapiro1 We didn't see a `total_units` attribute in this source data.

**Comment by mshapiro1** [comment]
@baolingz we should consider bringing in `total_units` from previous years. to be discussed at the meeting today!

**Comment by AmandaDoyle** [comment]
Get total_units from 2019 KPDB tracker and add to "manual research file

**Comment by mgraber** [comment]
Alter to get BBL-level polygon geometry from geosupport

**Comment by mgraber** [comment]
We are considering adding the total_units from the tracker directly to the input data. Going forward, total_units would be added in the data entry tab of the excel template. Does this seem reasonable?

**Comment by mshapiro1** [comment]
Yes. Thank you!

**Comment by mgraber** [comment]
@mshapiro1 Each record in the input data is a unique project and BBL combination. The tracker only has records referring to each project. When assigning the tracker `total_units` to the input data records, how should units be allocated between BBLs? Uniformly?
