### ISSUE TITLE
DOB matching: date constraint

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#82]
exclude matches where DOB date permitted year is > 2 years before other date year

**Comment by AmandaDoyle** [comment]
Need more information from @mshapiro1 but additional logic may be
If there is no date on the record then the DOB date permitted must be >= two year before the current year (ie if current year is 2020 date permitted must be >= 2018)

**Comment by mshapiro1** [comment]
@AmandaDoyle I concur with your proposed logic
