### ISSUE TITLE
DOB matching: Exclude negative alterations

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#83]
Need confirmation and clarification from @mshapiro1 on what unit value

**Comment by mshapiro1** [comment]
@AmandaDoyle units_net. confirming that these records should be included in the final KPDB, but excluded from clustering.

**Comment by mshapiro1** [comment]
@AmandaDoyle DOB records which are negative alterations can be excluded from clustering with all sources
