### ISSUE TITLE
Exclude DOB jobs with a units_net count of 0 from final KPDB and matching

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#84]
Need clarification from @mshapiro1 on what unit field and if there is general agreement

**Comment by mshapiro1** [comment]
@AmandaDoyle units_net. Received HED confirmation via @levysamu

**Comment by mshapiro1** [comment]
@levysamu do we want to exclude 0 unit jobs, as they are included in Housing DB?

@AmandaDoyle even if we include 0 unit jobs, they should definitely be excluded from clustering.

**Comment by levysamu** [comment]
I'm fine with excluding 0 unit jobs altogether. The purpose of KPDB is to show expected residential change. As far as I am concerned, 0 unit jobs do not meet that criteria.

**Comment by LubaPlanning** [comment]
Seems like y'all discussed this yesterday so I'm looking to get caught up - @levysamu @mshapiro1 What kinds of jobs are DOB projects with 0 units, and are there so many of them that there is a serious benefit to completely excluding these? 

I'd like to understand whether there is any argument that we could make that we shouldinclude them for the sake of completeness in including Housing DB within KPDB.

**Comment by levysamu** [comment]
@LubaPlanning, jobs that have 0 net units are those that are alterations in residential buildings that don't change the unit count. @mshapiro1 was saying that there were quite a few getting in the way during cluster analysis. Either remove them like I was suggesting, or just don't include them in clusters. Either way is fine with me.

**Comment by LubaPlanning** [comment]
Per today's meeting- CP and HED agreed to exclude DOB jobs with 0 units from clustering AND final KPDB.

**Comment by mgraber** [comment]
### Current status:

- Already excluded from matching
- Need to exclude from final table. Easiest method is probably to filter these out as part of dcp_housing.sql, prior to matching
