### ISSUE TITLE
Logic on how to handle and incorporate data from renewal records in ZAP

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#85]
Proposal: 
1) add corresponding ZAP ID to each ZAP renewal record
2) Update some attributes on the original record from the renewal record where it's available (i.e. number of units).  Need input from CP and HED
3) add column with ZAP renewal ID
4) continue on with regular processing

**Comment by SPTKL** [comment]
#78

**Comment by AmandaDoyle** [comment]
@LubaPlanning agreed to this process
@mshapiro1 and @SPTKL will finalize list of ZAP projects and ZAP renewals

**Comment by LubaPlanning** [comment]
In today's meeting HED, EDM, and CP agreed on item #2 in the list above: the only part of the original record that should be updated is unit count.

@SPTKL said he would look into adding a flag to indicate that units had been pulled from a renewal record.
