### ISSUE TITLE
status field

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#90]
Need guidance on status values if it's not going to be a straight mapping from the source

I'd prefer to normalize the status values and provide comprehensive metadata, as opposed to trying to jam information into the value (i.e. including more detailed information in the values used in the Status field, such as "DOB Complete - first CO issued," "ZAP Complete...").  Please let me know if you'd be open to normalize the status values, and if so, DE will make a proposal for you to edit.

In this case normalization would standardize status values
If X and Y both mean A, then the values for X and Y would both be changed to A in the final table
Another example if Complete and Active, Certified are synonymous then we could just have Complete

**Comment by kschmidtDCP** [comment]
I'm open to normalizing this, but I think it would be helpful to have a more detailed mapping of what values would be recoded into what. I share Luba's concern that "complete" as a status can be really misleading depending on that the data source is.

**Comment by AmandaDoyle** [comment]
@kschmidtDCP 
All of the unique statuses and their sources can be found [here](https://github.com/NYCPlanning/db-knownprojects/wiki/KPDB-status-normalization) 
If there are no relationships between status, and having the status directly from the source is important, then we don't need to normalize the values.  I was thinking that the normalization might be easier for end users

**Comment by LubaPlanning** [comment]
@kschmidtDCP, @levysamu, @mshapiro1 -  I like the proposed normalization. Do we think it's conceptually misleading to mark HPD projects as "financing closed" if DOB projects could also have financing closed but we don't have that information? In other words, does the normalization falsely track projects on a timeline, when we have incomplete information about the status of the actual project?

**Comment by mshapiro1** [comment]
@LubaPlanning I think that is conceptually misleading as well. I don't think it'd have an effect on how we track projects on timelines, though.

Also, I think it's still useful to have the source statuses as we review. We should only normalize them for the output.

**Comment by AmandaDoyle** [comment]
@kschmidtDCP @LubaPlanning @mshapiro1 
We can apply the normalization to only the final output
If you'd like to normalize we'd like you'd final value mapping by EOD Wednesday

**Comment by AmandaDoyle** [comment]
Did not receive information on how to move forward, so we will not be tackling this issue for this release

**Comment by AmandaDoyle** [comment]
Got info from capital planning
https://nyco365.sharepoint.com/:x:/s/NYCPLANNING/cp/EUI3-hLDek5Nnt5yg3dSIhEBGNiSXWhMxZxQok6I3B2xtg?e=xVuYfc
Normalization values are here

**Comment by SPTKL** [comment]
```sql
select distinct statecode, statuscode, dcp_projectphase, dcp_publicstatus 
from dcp_project
where dcp_name in (Select record_id from dcp_application)
```
![image](https://user-images.githubusercontent.com/13207770/81310802-96351280-9052-11ea-83cd-fbab369a01f6.png)
it seems like the zap status fields are more complicated than described in the spreadsheets

**Comment by SPTKL** [comment]
# ZAP status mapping
```sql
with 
zap_status as (select 
	dcp_name as record_id,
	(case
		when dcp_publicstatus ~* 'completed' then 'DCP 4: Zoning Implemented'
		when dcp_projectphase ~* 'project completed' then 'DCP 4: Zoning Implemented'
		when dcp_projectphase ~* 'pre-pas|pre-cert' then 'DCP 2: Application in progress'
		when dcp_projectphase ~* 'initiation' then 'DCP 1: Expression of interest'
		when dcp_projectphase ~* 'public review' then 'DCP 3: Certified/Referred'
	end) status
from dcp_project
where dcp_name in (Select record_id from kpdb."2020"))
update kpdb."2020" a
set status = b.status
from zap_status b
where a.record_id = b.record_id;
```

**Comment by mgraber** [comment]
Query to check non-ZAP mapping:
```sql
SELECT DISTINCT
source,
status as old_status,
(CASE 
WHEN source = 'DOB' 
	THEN 
		CASE
			WHEN inactive = '1' THEN 'DOB 9: Application inactive'
			WHEN status = 'Permit issued' THEN 'DOB 3: Construction permit issued'
			WHEN status = 'Partial complete' THEN 'DOB 4: CofO issued for part of building'
			WHEN status = 'In progress (last plan disapproved)' THEN 'DOB 2: Application in progress'
			WHEN status = 'Withdrawn' THEN NULL
			WHEN status = 'Complete (demolition)' THEN NULL
			WHEN status = 'Complete' THEN 'DOB 5: CofO issued for entire building'
			WHEN status = 'Filed' THEN 'DOB 1: Application filed'
			WHEN status = 'In progress' THEN 'DOB 2: Application in progress'
		END
WHEN source = 'EDC Projected Projects' AND status = 'Projected' THEN 'Potential'
WHEN source = 'Empire State Development Projected Projects' AND status = 'Projected' THEN 'Potential'
WHEN source = 'Future Neighborhood Studies' AND status = 'Projected' THEN 'Potential'
WHEN source = 'HPD Projected Closings' AND status = 'Projected' THEN 'HPD 3: Projected Closing'
WHEN source = 'HPD RFPs' 
	THEN 
		CASE
			WHEN status = 'RFP designated; financing closed' THEN 'HPD 4: Financing Closed'
			WHEN status = 'RFP designated; financing not closed' THEN 'HPD 2: RFP Designated'
			WHEN status = 'RFP issued; financing not closed' THEN 'HPD 1: RFP Issued'
		END
WHEN source = 'Neighborhood Study Projected Development Sites' AND status = 'Projected Development' THEN 'Potential'
WHEN source = 'Neighborhood Study Rezoning Commitments' AND status = 'Rezoning Commitment' THEN 'Potential'
END) as new_status
FROM kpdb."2020"
ORDER BY new_status;
```

**Comment by mgraber** [comment]
Not every DOB job marked as Complete (demolition) has an inactive flag. These are getting NULL status.

**Comment by SPTKL** [comment]
miscellaneous statuses (NULL, and other exceptions) will be filled through the corrections process

**Comment by AmandaDoyle** [comment]
@mgraber @SPTKL 
Not all records where the source is DOB and the status is Complete (demolition) should have an an inactive flag.  If the status is Complete (demolition) and inactive is NULL I propose the status to be "DOB 0: Building demolished"
